//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERITOR.StockRoom.Web.DIWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMP", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EMP : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PASSWORDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NAME {
            get {
                return this.NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.NAMEField, value) != true)) {
                    this.NAMEField = value;
                    this.RaisePropertyChanged("NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PASSWORD {
            get {
                return this.PASSWORDField;
            }
            set {
                if ((object.ReferenceEquals(this.PASSWORDField, value) != true)) {
                    this.PASSWORDField = value;
                    this.RaisePropertyChanged("PASSWORD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DIWebService.DIWebServiceSoap")]
    public interface DIWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        MERITOR.StockRoom.Web.DIWebService.HelloWorldResponse HelloWorld(MERITOR.StockRoom.Web.DIWebService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MERITOR.StockRoom.Web.DIWebService.HelloWorldResponse> HelloWorldAsync(MERITOR.StockRoom.Web.DIWebService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name e from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddService", ReplyAction="*")]
        MERITOR.StockRoom.Web.DIWebService.AddServiceResponse AddService(MERITOR.StockRoom.Web.DIWebService.AddServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddService", ReplyAction="*")]
        System.Threading.Tasks.Task<MERITOR.StockRoom.Web.DIWebService.AddServiceResponse> AddServiceAsync(MERITOR.StockRoom.Web.DIWebService.AddServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public MERITOR.StockRoom.Web.DIWebService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MERITOR.StockRoom.Web.DIWebService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MERITOR.StockRoom.Web.DIWebService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MERITOR.StockRoom.Web.DIWebService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddService", Namespace="http://tempuri.org/", Order=0)]
        public MERITOR.StockRoom.Web.DIWebService.AddServiceRequestBody Body;
        
        public AddServiceRequest() {
        }
        
        public AddServiceRequest(MERITOR.StockRoom.Web.DIWebService.AddServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MERITOR.StockRoom.Web.DIWebService.EMP[] e;
        
        public AddServiceRequestBody() {
        }
        
        public AddServiceRequestBody(MERITOR.StockRoom.Web.DIWebService.EMP[] e) {
            this.e = e;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public MERITOR.StockRoom.Web.DIWebService.AddServiceResponseBody Body;
        
        public AddServiceResponse() {
        }
        
        public AddServiceResponse(MERITOR.StockRoom.Web.DIWebService.AddServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddServiceResult;
        
        public AddServiceResponseBody() {
        }
        
        public AddServiceResponseBody(string AddServiceResult) {
            this.AddServiceResult = AddServiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DIWebServiceSoapChannel : MERITOR.StockRoom.Web.DIWebService.DIWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DIWebServiceSoapClient : System.ServiceModel.ClientBase<MERITOR.StockRoom.Web.DIWebService.DIWebServiceSoap>, MERITOR.StockRoom.Web.DIWebService.DIWebServiceSoap {
        
        public DIWebServiceSoapClient() {
        }
        
        public DIWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DIWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DIWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DIWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MERITOR.StockRoom.Web.DIWebService.HelloWorldResponse MERITOR.StockRoom.Web.DIWebService.DIWebServiceSoap.HelloWorld(MERITOR.StockRoom.Web.DIWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MERITOR.StockRoom.Web.DIWebService.HelloWorldRequest inValue = new MERITOR.StockRoom.Web.DIWebService.HelloWorldRequest();
            inValue.Body = new MERITOR.StockRoom.Web.DIWebService.HelloWorldRequestBody();
            MERITOR.StockRoom.Web.DIWebService.HelloWorldResponse retVal = ((MERITOR.StockRoom.Web.DIWebService.DIWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MERITOR.StockRoom.Web.DIWebService.HelloWorldResponse> MERITOR.StockRoom.Web.DIWebService.DIWebServiceSoap.HelloWorldAsync(MERITOR.StockRoom.Web.DIWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MERITOR.StockRoom.Web.DIWebService.HelloWorldResponse> HelloWorldAsync() {
            MERITOR.StockRoom.Web.DIWebService.HelloWorldRequest inValue = new MERITOR.StockRoom.Web.DIWebService.HelloWorldRequest();
            inValue.Body = new MERITOR.StockRoom.Web.DIWebService.HelloWorldRequestBody();
            return ((MERITOR.StockRoom.Web.DIWebService.DIWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MERITOR.StockRoom.Web.DIWebService.AddServiceResponse MERITOR.StockRoom.Web.DIWebService.DIWebServiceSoap.AddService(MERITOR.StockRoom.Web.DIWebService.AddServiceRequest request) {
            return base.Channel.AddService(request);
        }
        
        public string AddService(MERITOR.StockRoom.Web.DIWebService.EMP[] e) {
            MERITOR.StockRoom.Web.DIWebService.AddServiceRequest inValue = new MERITOR.StockRoom.Web.DIWebService.AddServiceRequest();
            inValue.Body = new MERITOR.StockRoom.Web.DIWebService.AddServiceRequestBody();
            inValue.Body.e = e;
            MERITOR.StockRoom.Web.DIWebService.AddServiceResponse retVal = ((MERITOR.StockRoom.Web.DIWebService.DIWebServiceSoap)(this)).AddService(inValue);
            return retVal.Body.AddServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MERITOR.StockRoom.Web.DIWebService.AddServiceResponse> MERITOR.StockRoom.Web.DIWebService.DIWebServiceSoap.AddServiceAsync(MERITOR.StockRoom.Web.DIWebService.AddServiceRequest request) {
            return base.Channel.AddServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<MERITOR.StockRoom.Web.DIWebService.AddServiceResponse> AddServiceAsync(MERITOR.StockRoom.Web.DIWebService.EMP[] e) {
            MERITOR.StockRoom.Web.DIWebService.AddServiceRequest inValue = new MERITOR.StockRoom.Web.DIWebService.AddServiceRequest();
            inValue.Body = new MERITOR.StockRoom.Web.DIWebService.AddServiceRequestBody();
            inValue.Body.e = e;
            return ((MERITOR.StockRoom.Web.DIWebService.DIWebServiceSoap)(this)).AddServiceAsync(inValue);
        }
    }
}
